name: CI
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: pack
      run: |
        cd ActivePerl
        choco pack
    - name: install
      run: |
        cd ActivePerl
        choco install -y ActivePerl -dv -s .
    - name: push
      run: |
        cd ActivePerl
        choco push -k="'TODO'" ActivePerl
